ZO-2395: Introduce new navigations to Zappi Specs
ZeitOnline/docs-zappi pull request #109
Opened 2023-01-27 08:35 UTC by thomaspuppe

(Diskussion zur Benamung am Ticket https://zeit-online.atlassian.net/browse/ZO-2395 )

2023-01-27 13:03 UTC, TStrothjohann reviewed
Hi @thomaspuppe,
Danke für den PR bzw. Deine Arbeit. 

Meine inhaltlich größte Frage zu Deinen Änderungen ist folgende: die App hatte bisher ein Menu. Ist es wirklich sinnvoll, das Menu jetzt durch Navigationen zu ersetzen?

Zu Deiner Frage mit den Checks: mir wäre lieb, wenn nur die Sachen streng definiert würden, die wir definitiv einheitlich haben wollen. Die Zeichenzahl eines Titels gehört für mich nicht dazu. Und beim menu-item-tab-start sollte die url mE auch nicht required sein, weil sie es in Wahrheit nicht ist. Die App sieht: "ah. Da wurde ein menu-item-tab-start angeklickt - dann zeige ich den Tab im Initialzustand. url/source/target ist an der Stelle irrelevant.

Bisher sind die Versionen der Apps nur intern releast, die `menus` etc. erwarten. Aber ich muss die iOS- und Android-Entwickler dann bitten, den Code anzupassen. Eigentlich müssten wir viel enger zusammenarbeiten, damit ihr wisst, was wir machen und die API sich nach Euren Standards entwickelt. Bin etwas ratlos.

2023-01-27 13:04 UTC, TStrothjohann commented on docs/api/api.yaml
> +          minLength: 1
Ah. Nullable sollten die titles sein. Denn es gibt ja Sections, die keinen haben. Oder wäre dann ein Leerstring korrekt?

2023-01-31 12:06 UTC, thomaspuppe commented on docs/api/api.yaml
> +          example: "Start"
Okay, ich habe "Menü" ins Beispiel reingeschrieben.

2023-01-31 12:09 UTC, thomaspuppe commented on docs/api/api.yaml
> +          minLength: 1
Das hier sind die Titles der Navigation/Menü selbst. Nicht die der Sections. Aber sowohlk die Navigationen/Menüs als auch die Sections haben den Titel optional (weil: nicht required). Ich habe deine Demo-Struktur angepasst, damit das direkt in die Tests einfließt.

2023-02-02 15:15 UTC, louika approved these changes
passt 👍

2023-02-02 15:24 UTC, louika commented
ok moment, wo ist die Definition für `menu-left` und `menu-right` im Starttab? Kannst du mir da nochmal auf die Sprünge helfen @thomaspuppe ?

2023-02-02 15:33 UTC, louika requested changes
siehe oben

2023-02-03 09:26 UTC, louika approved these changes
Fine by me 👍

2023-02-03 09:26 UTC, louika commented on docs/api/api.yaml
> +            - user-menu
diese `enum` Definition heißt in der Realität, dass das Menü links immer das `content-menu` ist und das rechte Menü immer das `user-menu`. Siehe https://swagger.io/docs/specification/data-models/enums/ .Ich nehme an, das ist gewollt?

2023-02-03 09:26 UTC, louika commented on docs/api/api.yaml
> +            - user-menu
Bin immer noch etwas ratlos, das dass keinen `ValidationError` gegeben hat 🤔 weil es eben kein Schema dafür gab. Aber das funktioniert auch im master einfach...

2023-02-03 09:41 UTC, merged