ZON-6248: add Advertisement attribute to api
ZeitOnline/docs-zappi pull request #31
Opened 2020-11-16 15:01 UTC by louika

### Was erledigt dieser PR?
Fügt einen Merklisten Endpunkt für ZAPPI hinzu.

### Wo geht's los?
docs-zappi/api.yaml
zeit.web/app/view_readinglists.py

### Wie kann getestet werden?
im friedbert-deployment
$ bin/test zeit.web/src/zeit/web/app/test/test_view_bookmarks.py

### Relevante Tickets
https://zeit-online.atlassian.net/browse/ZON-6178

2020-11-16 15:18 UTC, tomster requested changes
und irgendwie scheint auch das yaml syntaktisch gelitten zu haben, jenkins sagt dinge wie ``No enum match for: bool at #/properties/hasAdvertisement/type``

2020-11-16 15:18 UTC, tomster commented on api.yaml
> +                  example: "true/false"
also, das example ist definitiv syntaktisch falsch... ich denke, beim type `bool` kann man es sich auch komplett sparen

2020-11-16 15:26 UTC, louika commented on api.yaml
> +                  example: "true/false"
ist entfernt

2020-11-18 09:39 UTC, tomster approved these changes

2020-11-18 09:39 UTC, merged