ZON-6153: Zappi adplaces
ZeitOnline/docs-zappi pull request #43
Opened 2020-12-23 16:41 UTC by louika

### Was erledigt dieser PR?

Fügt der Api Adplaces auf Centerpage-Ebene hinzu.

### Wo geht's los?

`api.yaml`

### Wie kann getestet werden?
wenn der zugehörige zeit.web PR gemerged ist:
`bin/test zeit.web/src/zeit/web/app/test/test_view_centerpage.py`

### Relevante Tickets

https://zeit-online.atlassian.net/browse/ZON-6153

### Gif

![dinner](https://media.giphy.com/media/3o6wraN6dQQ0KvimNG/giphy.gif)

2021-01-04 09:29 UTC, tomster requested changes
sieht gut aus, nur zwei winzigkeiten

2021-01-04 09:29 UTC, tomster commented on api.yaml
> +      description: "A place reserved an advertisement used by the iqd"
das ist noch a bisserl holprig. vielleicht "Placeholder for advertisement"?

2021-01-04 09:29 UTC, tomster commented on api.yaml
> +              - mobile
nur der form halber: gibt es auch ads, die sowohl desktop also auch mobile sein koennen? falls ja, wuerde das diese API nicht abbilden koennen bzw. nur durch dopplung der adplacements. falls nein, bin ich wieder still :)

2021-01-04 15:31 UTC, mstoltenburg commented on api.yaml
> +              - mobile
nö, jibt's nich

2021-01-04 16:08 UTC, mstoltenburg commented on api.yaml
> +          id:
Ich finde sowohl `id` als auch `device` leider etwas zwiespältige Bezeichnungen, vor allem `id` - auch wenn wir die bedauernswerter weise genau so in zeit.web verwenden. Die _anderen_ CP Elemente haben in der id ja den Vivi-Namen stehen - die Adplaces nicht besitzen. 
`id` = IQD ad tile number (`tile`? `id`?)
`device` = media (`media`? `type`? `device`?) 🤷🏼‍♂️ 
Im HTML ist es z.B. `data-type="desktop" data-tile="1"`

2021-01-05 10:05 UTC, louika commented on api.yaml
> +              - adplace
das habe ich aus der zeit.web.core.module.adplace übernommen. Ist das generell ein Platzhalter und hat keine Funktion?

2021-01-05 10:16 UTC, louika commented on api.yaml
> +            $ref: "#/components/schemas/CenterpageElementType"
Meiner Meinung nach ist der Adplace ist eher analog zur Region, die ein CpElement ist. Die Teaser Types sind noch in CenterpageElementType eingetragen, daher war das auf den ersten Blick kein Widerspruch https://github.com/ZeitOnline/docs-zappi/blob/cdfe05f25bcb4578a4ac50ef9402c0b5cd04a85a/api.yaml#L302-L305

2021-01-05 10:28 UTC, louika commented on api.yaml
> +          id:
`id` ist in `tile` umbenannt. `type` bedeutet in diesem Kontext eher `adplace, area, region, teaser`, auch wenn es im HTML so benannt ist. `device` verdeutlicht, ob es sich um ein Desktop der Mobil Adplace handelt. Benötigen wir in der App überhaupt Desktop-Adplaces?

2021-01-06 12:39 UTC, tomster approved these changes

2021-01-06 12:39 UTC, merged