add submenu to structure and add quote marks
ZeitOnline/docs-zappi pull request #55
Opened 2021-02-03 17:34 UTC by Rosebudlia

2021-02-04 09:56 UTC, tomster requested changes
hi rose, two issues:

firstly, you should separate two changes into two separate commits, i.e. one where you add the structure and another where you clean up the quotes
secondly, when cleaning up the quotes, we should simply keep the quotes we use consistent but not add them to *all* strings, since yaml doesn't require them everywhere.

2021-02-04 10:38 UTC, louika commented
Dont merge until submenu is valid item of `tab-menu` item type.

2021-02-11 09:34 UTC, tomster requested changes
the submenu item looks good, but there are still too many superfluous quotation marks being added in this PR

2021-02-12 10:03 UTC, louika commented
Nach Hinzufügen der Anführungszeichen durch @Rosebudlia deckt sich das Beispiel mit der Auslieferung durch Zappi, siehe https://zappi.zeit.de/0.3.1/structure
das ist IMHO ne gute Sache.

2021-02-15 09:19 UTC, tomster commented
> Nach Hinzufügen der Anführungszeichen durch @Rosebudlia deckt sich das Beispiel mit der Auslieferung durch Zappi, siehe https://zappi.zeit.de/0.3.1/structure
> das ist IMHO ne gute Sache.

ja, dass das rendering um alles anfuehrungszeichen macht ist sinnvoll (weil es aufwaendig waere dem beizubringen zu erkennen, wann es notwendig ist und wann nicht) aber im quell-yaml vermeiden wir unnoetige anfuehrungszeichen, weil das sonst nur unnoetig viel cargo cult beim schreiben erzeugt. also zumindest halten wir das in allen yaml files im ops-bereich so (und da haben wir mittlerweile hunderte davon). ich wuerde das gerne weiterhin einheitlich halten und euch bitten, die anfuehrungszeichen wieder zu entfernen und nur dort welche zu haben, wo es notwendig ist. sorry noch mal fuer das missverstaendnis eingangs, rose hatte ja extra nachgefragt, aber wir hatten leider aneinander vorbeigeredet.

2021-02-15 09:36 UTC, tomster commented
anfuehrungszeichen werden eigentlich nur dort gebraucht, wo ihr fehlen zu invalidem yaml fuehren 

a) wuerde (also zb, bei den "vollen" uuid notation mit den geschweiften klammern
b) koennte (bei urls z.b., deshalb lieber auf nummer sicher gehen und urls quoten

oder c) nicht eindeutig waere (z.b. wenn eine zahl als string notiert werden soll (also ``"12"`` weil ``12`` sonst als integer interpretiert werden wuerde)

2021-02-15 11:07 UTC, Rosebudlia commented
@tomster  danke fürs Feedback, ich korrigiere die Quotation Marks :) und ja das ist doof mit den blöd aufgeteilten Commits, sorry - das war ein Fehler, die staged Changes gingen ein bisschen durcheinander...

2021-02-15 11:56 UTC, Rosebudlia commented
Ok @tomster bitte nochmal prüfen?

2021-02-15 12:18 UTC, tomster approved these changes
perfect

2021-02-15 12:18 UTC, merged