ZON-6143: provide image count for galleries
ZeitOnline/docs-zappi pull request #6
Opened 2020-09-22 14:22 UTC by tomster

2020-09-22 14:32 UTC, tomster commented
run jenkins

2020-09-24 12:24 UTC, wosc requested changes
Ich fürchte da fehlt noch was. :)

2020-09-24 12:24 UTC, wosc commented on api.yaml
> +        - properties:
Vermutlich wollen wir dann einen spezielleren `type` verwenden? Also nicht `type=teaser`, sondern `type=gallery` oder so? (vgl https://github.com/zeitonline/docs-app-api/blob/master/api.yaml#L156-L160)

2020-09-24 12:24 UTC, wosc commented on api.yaml
> +    CenterPageModuleImageGallery:
Damit das was nutzt, muss dieser Typ bei [CenterpageArea/items](https://github.com/zeitonline/docs-app-api/blob/master/api.yaml#L286) als Möglichkeit aufgeführt werden.

(Und vmtl reicht `CenterpageModuleGallery` als Bezeichner?)

2020-09-24 13:41 UTC, mstoltenburg commented on api.yaml
> +        - properties:
Mir ist noch nicht klar, was type: teaser noch für Werte annehmen können soll. Was gibt es denn noch für Typen? Ich habe ja gleichzeitig mit Thomas über die Teaser geschaut, und wir hatten ähnliche Ideen, aber das geht jetzt in Richtung _naming things_ siehe https://hackmd.zeit.de/ULtktZi-QHOPsrRPRi4Dsw#Teaser

Wie dort zu sehen brauchen wir
- Kolumnenteaser (braucht Autorenbild)
- Podcast-Teaser (enthält Podcast)
- Video-Teaser (contenttyp: video, hat brightcoveID o.ä.)
- BiGa (contenttyp: gallery, hat image-count)

Mir schweben dafür Namen vor wie
`CenterpageModuleTeaser`
`CenterpageModuleTeaserGallery`
`CenterpageModuleTeaserVideo`
`CenterpageModuleTeaserPodcast`
`CenterpageModuleTeaserColumn`

Man kann auch noch diskutieren: Ist das Autorenbild für Kolumnenteaser einfach ein optionales Attribut des `CenterpageModuleTeaser`? Deckt man mit `CenterpageModuleTeaser` einfach alle genannten Teaser ab, und hat dann type: `teaser`, `gallery`, `video`, `column` etc. (i don't like it)?

2020-09-24 14:20 UTC, wosc commented on api.yaml
> +        - properties:
Hurra, naming things. Strukturell hast Du völlig Recht, dass das alles Teaser-Module sind (Teaser auf Artikel&Co, Teaser auf Gallery, Teaser auf Video etc.pp.), im Gegensatz zu Raw- oder Headerimage- oder Markup-Modulen.

Insofern wäre `type=teaser-gallery` (und `CenterpageModuleTeaserGallery`) genau das richtige. Da jetzt künstlich das Wort "Teaser" einsparen zu wollen, bringt glaub nirgends eine wirkliche Erleichterung, weiß gar nicht, warum ich in die Richtung abgebogen bin.

2020-09-24 16:05 UTC, mstoltenburg commented on api.yaml
> +        - properties:
Da sollten wir noch mal generell draufsehen. Mein Bauch sagt mir gerade `CenterpageModuleTeaserGallery` und `type=teaser`, aber vielleicht ist das morgen schon anders.

2020-09-29 14:44 UTC, tomster commented
gehe ueber los, ziehe nicht 400 mark ein

2020-09-29 14:44 UTC, closed without merging